### ISSUE TITLE
I can't build the example plugin

### ISSUE THREAD

**Issue by HuQisQwQ** [EndstoneMC/cpp-plugin-template#1]
I tried to build the example plugin, when I execute "cmake --build .", It will.......................

fmtd.lib(format.obj) : error LNK2038: 检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(example_plugin.obj
中) [D:\cpp-example-plugin\build\cpp_example.vcxproj]
    正在创建库 D:/cpp-example-plugin/build/Debug/cpp_example.lib 和对象 D:/cpp-example-plugin/build/Debug/cpp_
  example.exp
D:\cpp-example-plugin\build\Debug\endstone_cpp_example.dll : fatal error LNK1319: 检测到 1 个不匹配项 [D:\cpp-
example-plugin\build\cpp_example.vcxproj]

**Comment by wu-vincent** [comment]
Please try to delete the build folder and do a clean rebuild. Also make sure you set the build type to Release or RelWithDebInfo. The debug builds are not ABI compatible with endstone and BDS.

**Comment by wu-vincent** [comment]
Please feel free to reopen the issue if the problem still exists.
